#exo2
Début 
    J'ai un panier vide
    Tant que mon panier n'a pas 10 pommes FAIRE
    Je queille 1 pomme et la met dans mon panier
    fin de tant que
    J'annonce que j'ai un panier plein
Fin

@startuml

start
:Instancier un panier vide = 0;
:Instacier Taille max de panier = 10;
repeat
    :ajouter une pomme dans le panier ; panier + 1;
repeat while (panier < max panier) 
:message "panier plein";
stop

@enduml