#exo2
Début 
    J'ai 5 plantes
    Tant que je n'ai pas arrosé mes 5 plantes faire
    arroser une plante
    fin tant que
    annoncer toutes les plantes ont eu de l'eau
Fin

@startuml

start
:Instancier nombre de plantes = 5 
:IInstantier plantes à arroser = 0
while (plante à arroser < nb plantes) is (yes)
    :arroser une plante
endwhile
:message "toutes les plantes sont arrosées";
stop

@enduml